spring.application.name=recycling-api
server.port=8081

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3-flash-preview